services:
  postgres:
    image: ankane/pgvector
    container_name: oli_postgres
    logging:
      driver: "json-file"
      options:
        max-file: "1"
        max-size: 5m
    ports:
      - 5432:5432
    env_file: ./postgres.env
    volumes:
      - pg_data:/var/lib/postgresql/data

  minio:
    image: minio/minio
    container_name: oli_minio
    env_file: ./oli.env
    entrypoint: /bin/sh
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - minio_data:/data
    command:
      - -c
      - exec env MINIO_ROOT_USER="$$AWS_ACCESS_KEY_ID" MINIO_ROOT_PASSWORD="$$AWS_SECRET_ACCESS_KEY" minio server --console-address :9001 /data

  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: oli_clickhouse
    ports:
      - 8123:8123
      - 9090:9000
      - 9009:9009
    volumes:
      - clickhouse_data:/var/lib/clickhouse
      - ./clickhouse/users.xml:/etc/clickhouse-server/users.d/dev-users.xml

  haproxy:
    build:
      context: ./scripts/dev/ha-proxy
      dockerfile: Dockerfile
    container_name: oli_haproxy
    depends_on:
      - minio
    env_file: ./oli.env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - 80:80
      - 443:443

volumes:
  pg_data:
  minio_data:
  clickhouse_data:
