version: "3.5"
services:
  app:
    build: .
    depends_on:
      - postgres
    env_file: ./oli.env
    ports:
      - 80:80
      - 443:443

  postgres:
    image: ankane/pgvector
    logging:
      driver: "json-file"
      options:
        max-file: "1"
        max-size: 5m
    ports:
      - 5432:5432
    env_file: ./postgres.env
    volumes:
      - postgres_data1:/var/lib/postgresql/data
    container_name: torus
    networks:
      - net

  localstack:
    container_name: aws
    image: localstack/localstack
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"  # external services port range
    environment:
      # LocalStack configuration: https://docs.localstack.cloud/references/configuration/
      - AWS_DEFAULT_REGION=us-east-1
      - SERVICES=s3,sqs
      - DEBUG=${DEBUG:-0}
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - DISABLE_CORS_CHECKS=1
      - PROVIDER_OVERRIDE_S3=asf
      - S3_SKIP_SIGNATURE_VALIDATION=1
      - PERSISTENCE=1
    volumes:
      - "./localstack.config/init-aws.sh:/etc/localstack/init/ready.d/init-aws.sh"  # ready hook
      - "./localstack.config/queue-config.json:/etc/localstack/init/ready.d/config/queue-config.json"  # queue config file
      - "./aws:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - net

volumes:
  postgres_data1:

networks:
  net:
    external: true
