services:
  postgres:
    image: ankane/pgvector
    container_name: oli_postgres
    logging:
      driver: "json-file"
      options:
        max-file: "1"
        max-size: 5m
    ports:
      - 5432:5432
    env_file: ./postgres.env
    volumes:
      - postgres_data:/var/lib/postgresql/data

  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: oli_clickhouse
    ports:
      - 8123:8123
      - 9090:9000
      - 9009:9009
    volumes:
      - clickhouse_data:/var/lib/clickhouse
      - ./clickhouse/users.xml:/etc/clickhouse-server/users.d/dev-users.xml

  haproxy:
    build:
      context: ./scripts/dev/ha-proxy
      dockerfile: Dockerfile.docker
    container_name: oli_haproxy
    env_file: ./oli.env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - 80:80
      - 443:443

volumes:
  postgres_data:
  minio_data:
  clickhouse_data:
