{{- if .Values.postgres.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "oli-torus-preview.postgresName" . }}
  labels:
    {{- include "oli-torus-preview.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
  selector:
    {{- include "oli-torus-preview.selectorLabels" . | nindent 4 }}
    component: postgres
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "oli-torus-preview.postgresName" . }}
  labels:
    {{- include "oli-torus-preview.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "oli-torus-preview.postgresName" . }}
  replicas: 1
  selector:
    matchLabels:
      {{- include "oli-torus-preview.selectorLabels" . | nindent 6 }}
      component: postgres
  template:
    metadata:
      labels:
        {{- include "oli-torus-preview.selectorLabels" . | nindent 8 }}
        component: postgres
    spec:
      containers:
        - name: postgres
          image: {{ .Values.postgres.image }}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5432
              name: postgres
          env:
            - name: POSTGRES_USER
              value: {{ .Values.postgres.auth.username | quote }}
            - name: POSTGRES_PASSWORD
              value: {{ .Values.postgres.auth.password | quote }}
            - name: POSTGRES_DB
              value: {{ .Values.postgres.auth.database | quote }}
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
            - name: POSTGRES_HOST_AUTH_METHOD
              value: trust
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
          readinessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - pg_isready -U {{ .Values.postgres.auth.username }} -h 127.0.0.1
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - pg_isready -U {{ .Values.postgres.auth.username }} -h 127.0.0.1
            initialDelaySeconds: 30
            periodSeconds: 10
          {{- with .Values.postgres.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          {{- range .Values.postgres.persistence.accessModes }}
          - {{ . }}
          {{- end }}
        {{- if .Values.postgres.persistence.storageClass }}
        storageClassName: {{ .Values.postgres.persistence.storageClass }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.postgres.persistence.size }}
{{- end }}
