defmodule Oli.LanguageCodesIso639 do
  def codes() do
    [
      "Abkhaz [ab]": "ab",
      "Afar [aa]": "aa",
      "Afrikaans [af]": "af",
      "Akan [ak]": "ak",
      "Albanian [sq]": "sq",
      "Amharic [am]": "am",
      "Arabic [ar]": "ar",
      "Aragonese [an]": "an",
      "Armenian [hy]": "hy",
      "Assamese [as]": "as",
      "Avaric [av]": "av",
      "Avestan [ae]": "ae",
      "Aymara [ay]": "ay",
      "Azerbaijani [az]": "az",
      "Bambara [bm]": "bm",
      "Bashkir [ba]": "ba",
      "Basque [eu]": "eu",
      "Belarusian [be]": "be",
      "Bengali [bn]": "bn",
      "Bihari [bh]": "bh",
      "Bislama [bi]": "bi",
      "Bosnian [bs]": "bs",
      "Breton [br]": "br",
      "Bulgarian [bg]": "bg",
      "Burmese [my]": "my",
      "Catalan; Valencian [ca]": "ca",
      "Chamorro [ch]": "ch",
      "Chechen [ce]": "ce",
      "Chichewa; Chewa; Nyanja [ny]": "ny",
      "Chinese [zh]": "zh",
      "Chuvash [cv]": "cv",
      "Cornish [kw]": "kw",
      "Corsican [co]": "co",
      "Cree [cr]": "cr",
      "Croatian [hr]": "hr",
      "Czech [cs]": "cs",
      "Danish [da]": "da",
      "Divehi; Dhivehi; Maldivian; [dv]": "dv",
      "Dutch [nl]": "nl",
      "English [en]": "en",
      "Esperanto [eo]": "eo",
      "Estonian [et]": "et",
      "Ewe [ee]": "ee",
      "Faroese [fo]": "fo",
      "Fijian [fj]": "fj",
      "Finnish [fi]": "fi",
      "French [fr]": "fr",
      "Fula; Fulah; Pulaar; Pular [ff]": "ff",
      "Galician [gl]": "gl",
      "Georgian [ka]": "ka",
      "German [de]": "de",
      "Greek, Modern [el]": "el",
      "Guaraní [gn]": "gn",
      "Gujarati [gu]": "gu",
      "Haitian; Haitian Creole [ht]": "ht",
      "Hausa [ha]": "ha",
      "Hebrew (modern) [he]": "he",
      "Herero [hz]": "hz",
      "Hindi [hi]": "hi",
      "Hiri Motu [ho]": "ho",
      "Hungarian [hu]": "hu",
      "Interlingua [ia]": "ia",
      "Indonesian [id]": "id",
      "Interlingue [ie]": "ie",
      "Irish [ga]": "ga",
      "Igbo [ig]": "ig",
      "Inupiaq [ik]": "ik",
      "Ido [io]": "io",
      "Icelandic [is]": "is",
      "Italian [it]": "it",
      "Inuktitut [iu]": "iu",
      "Japanese [ja]": "ja",
      "Javanese [jv]": "jv",
      "Kalaallisut, Greenlandic [kl]": "kl",
      "Kannada [kn]": "kn",
      "Kanuri [kr]": "kr",
      "Kashmiri [ks]": "ks",
      "Kazakh [kk]": "kk",
      "Khmer [km]": "km",
      "Kikuyu, Gikuyu [ki]": "ki",
      "Kinyarwanda [rw]": "rw",
      "Kirghiz, Kyrgyz [ky]": "ky",
      "Komi [kv]": "kv",
      "Kongo [kg]": "kg",
      "Korean [ko]": "ko",
      "Kurdish [ku]": "ku",
      "Kwanyama, Kuanyama [kj]": "kj",
      "Latin [la]": "la",
      "Luxembourgish, Letzeburgesch [lb]": "lb",
      "Luganda [lg]": "lg",
      "Limburgish, Limburgan, Limburger [li]": "li",
      "Lingala [ln]": "ln",
      "Lao [lo]": "lo",
      "Lithuanian [lt]": "lt",
      "Luba-Katanga [lu]": "lu",
      "Latvian [lv]": "lv",
      "Manx [gv]": "gv",
      "Macedonian [mk]": "mk",
      "Malagasy [mg]": "mg",
      "Malay [ms]": "ms",
      "Malayalam [ml]": "ml",
      "Maltese [mt]": "mt",
      "Māori [mi]": "mi",
      "Marathi (Marāṭhī) [mr]": "mr",
      "Marshallese [mh]": "mh",
      "Mongolian [mn]": "mn",
      "Nauru [na]": "na",
      "Navajo, Navaho [nv]": "nv",
      "Norwegian Bokmål [nb]": "nb",
      "North Ndebele [nd]": "nd",
      "Nepali [ne]": "ne",
      "Ndonga [ng]": "ng",
      "Norwegian Nynorsk [nn]": "nn",
      "Norwegian [no]": "no",
      "Nuosu [ii]": "ii",
      "South Ndebele [nr]": "nr",
      "Occitan [oc]": "oc",
      "Ojibwe, Ojibwa [oj]": "oj",
      "Old Church Slavonic, Church Slavic, Church Slavonic, Old Bulgarian, Old Slavonic [cu]":
        "cu",
      "Oromo [om]": "om",
      "Oriya [or]": "or",
      "Ossetian, Ossetic [os]": "os",
      "Panjabi, Punjabi [pa]": "pa",
      "Pāli [pi]": "pi",
      "Persian [fa]": "fa",
      "Polish [pl]": "pl",
      "Pashto, Pushto [ps]": "ps",
      "Portuguese [pt]": "pt",
      "Quechua [qu]": "qu",
      "Romansh [rm]": "rm",
      "Kirundi [rn]": "rn",
      "Romanian, Moldavian, Moldovan [ro]": "ro",
      "Russian [ru]": "ru",
      "Sanskrit (Saṁskṛta) [sa]": "sa",
      "Sardinian [sc]": "sc",
      "Sindhi [sd]": "sd",
      "Northern Sami [se]": "se",
      "Samoan [sm]": "sm",
      "Sango [sg]": "sg",
      "Serbian [sr]": "sr",
      "Scottish Gaelic; Gaelic [gd]": "gd",
      "Shona [sn]": "sn",
      "Sinhala, Sinhalese [si]": "si",
      "Slovak [sk]": "sk",
      "Slovene [sl]": "sl",
      "Somali [so]": "so",
      "Southern Sotho [st]": "st",
      "Spanish; Castilian [es]": "es",
      "Sundanese [su]": "su",
      "Swahili [sw]": "sw",
      "Swati [ss]": "ss",
      "Swedish [sv]": "sv",
      "Tamil [ta]": "ta",
      "Telugu [te]": "te",
      "Tajik [tg]": "tg",
      "Thai [th]": "th",
      "Tigrinya [ti]": "ti",
      "Tibetan Standard, Tibetan, Central [bo]": "bo",
      "Turkmen [tk]": "tk",
      "Tagalog [tl]": "tl",
      "Tswana [tn]": "tn",
      "Tonga (Tonga Islands) [to]": "to",
      "Turkish [tr]": "tr",
      "Tsonga [ts]": "ts",
      "Tatar [tt]": "tt",
      "Twi [tw]": "tw",
      "Tahitian [ty]": "ty",
      "Uighur, Uyghur [ug]": "ug",
      "Ukrainian [uk]": "uk",
      "Urdu [ur]": "ur",
      "Uzbek [uz]": "uz",
      "Venda [ve]": "ve",
      "Vietnamese [vi]": "vi",
      "Volapük [vo]": "vo",
      "Walloon [wa]": "wa",
      "Welsh [cy]": "cy",
      "Wolof [wo]": "wo",
      "Western Frisian [fy]": "fy",
      "Xhosa [xh]": "xh",
      "Yiddish [yi]": "yi",
      "Yoruba [yo]": "yo",
      "Zhuang, Chuang [za]": "za"
    ]
  end
end
