name: "Torus Builder"
description: "Build Torus App for Production"
inputs:
  build-sha:
    description: "SHA of the build commit"
    required: true
runs:
  using: "docker"
  ## Use the prebuilt, cached torus-builder image from an earlier step
  image: torus-builder:latest
  args:
    - ${{ inputs.build-sha }}
