apiVersion: batch/v1
kind: Job
metadata:
  name: minio-buckets
  labels:
    app.kubernetes.io/component: minio
spec:
  backoffLimit: 6
  ttlSecondsAfterFinished: 3600
  template:
    metadata:
      labels:
        app.kubernetes.io/component: minio
    spec:
      restartPolicy: OnFailure
      containers:
        - name: create-buckets
          image: minio/mc:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: MINIO_ENDPOINT
              value: http://minio:9000
            - name: MINIO_ROOT_USER
              value: minio-user
            - name: MINIO_ROOT_PASSWORD
              value: minio-password
          command:
            - /bin/sh
            - -c
            - |
              set -euo pipefail
              until mc alias set local "$MINIO_ENDPOINT" "$MINIO_ROOT_USER" "$MINIO_ROOT_PASSWORD"; do
                echo "Waiting for MinIO..."
                sleep 3
              done
              mc mb --ignore-existing local/torus-media
              mc anonymous set public local/torus-media
              mc mb --ignore-existing local/torus-xapi
              mc anonymous set public local/torus-xapi
              mc mb --ignore-existing local/torus-blob-dev
              mc anonymous set public local/torus-blob-dev
          resources:
            requests:
              cpu: 200m
              memory: 512Mi
            limits:
              cpu: 500m
              memory: 1Gi
