name: "Amazon Linux Builder"
description: "Build Torus for Amazon Linux"
inputs:
  build-sha:
    description: "SHA of the build commit"
    required: true
runs:
  using: "docker"
  image: "Dockerfile"
  ## Use the prebuilt builder image on docker hub until github improves caching across builds
  # image: ghcr.io/simon-initiative/amazon-linux-builder:1.3.2
  args:
    - ${{ inputs.build-sha }}
