version: "3.5"
services:
  app:
    build:
      # Set the context to the parent directory, so we can add `.tool-versions` to the container
      context: ../
      dockerfile: .devcontainer/Dockerfile
      args:
        - ELIXIR_VERSION=1.17.2
        - OTP_VERSION=27.0.1
        - DEBIAN_VERSION=bullseye-20240722-slim
    depends_on:
      - postgres
    env_file: ../oli.env
    environment:
      MIX_ENV: dev
      DB_HOST: postgres
    volumes:
      - ../:/workspace/oli-torus
    # Overrides default command so things don't shut down after the process ends.
    command: bash -c "sleep infinity"

  postgres:
    image: ankane/pgvector
    restart: always
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - postgres_data:/var/lib/postgresql/data

  minio:
    image: minio/minio
    environment:
      MINIO_ROOT_USER: your_minio_access_key
      MINIO_ROOT_PASSWORD: your_minio_secret_key
    volumes:
      - minio_data:/data
    command: ["server", "--console-address", ":9001", "/data"]

volumes:
  postgres_data:
  minio_data:
