FROM haproxy:3.3.6

USER root

RUN mkdir -p /certs
COPY combined.pem /certs/combined.pem

COPY haproxy_docker.cfg /usr/local/etc/haproxy/haproxy.cfg.template
COPY docker-entrypoint-regular.sh /usr/local/bin/docker-entrypoint-regular.sh
RUN chmod +x /usr/local/bin/docker-entrypoint-regular.sh

USER haproxy

ENTRYPOINT ["/usr/local/bin/docker-entrypoint-regular.sh"]
