export const transformedSchema = {
  id: 'mcqFavorite',
  type: 'janus-mcq',
  Position: {
    x: 510,
    y: 130,
    z: 0,
  },
  Size: {
    width: 471,
    height: 100,
  },
  custom: {
    overrideHeight: false,
    palette: {
      backgroundColor: 'rgba(255,255,255,0)',
      borderColor: 'rgba(255,255,255,0)',
      borderRadius: '',
      borderStyle: 'solid',
      borderWidth: '1px',
      fillAlpha: 0,
      fillColor: 16777215,
      lineAlpha: 0,
      lineColor: 16777215,
      lineStyle: 0,
      lineThickness: 0.1,
      useHtmlProps: true,
    },
    fontSize: 12,
    layoutType: 'verticalLayout',
    showOnAnswersReport: false,
    requireManualGrading: false,
    showLabel: false,
    multipleSelection: false,
    randomize: false,
    showNumbering: false,
    mcqItems: [
      {
        nodes: [
          {
            style: {},
            children: [],
            alt: '',
            height: 0,
            href: '',
            src: '',
            tag: 'p',
            target: '',
            text: 'winter',
            width: 0,
          },
        ],
        scoreValue: 0,
      },
      {
        nodes: [
          {
            style: {},
            children: [],
            alt: '',
            height: 0,
            href: '',
            src: '',
            tag: 'p',
            target: '',
            text: 'spring',
            width: 0,
          },
        ],
        scoreValue: 0,
      },
      {
        nodes: [
          {
            style: {},
            children: [],
            alt: '',
            height: 0,
            href: '',
            src: '',
            tag: 'p',
            target: '',
            text: 'summer',
            width: 0,
          },
        ],
        scoreValue: 0,
      },
      {
        nodes: [
          {
            style: {},
            children: [],
            alt: '',
            height: 0,
            href: '',
            src: '',
            tag: 'p',
            target: '',
            text: 'fall',
            width: 0,
          },
        ],
        scoreValue: 0,
      },
    ],
    enabled: true,
    $schema: '',
    borderAlpha: 0,
    borderColor: 0,
    customCssClass: '',
    height: 100,
    maxManualGrade: 0,
    verticalGap: 0,
    width: 471,
    x: 510,
    y: 130,
    z: 0,
  },
};

export const componentData = {
  overrideHeight: false,
  palette: {
    backgroundColor: 'rgba(255,255,255,0)',
    borderColor: 'rgba(255,255,255,0)',
    borderRadius: '',
    borderStyle: 'solid',
    borderWidth: '1px',
    fillAlpha: 0,
    fillColor: 16777215,
    lineAlpha: 0,
    lineColor: 16777215,
    lineStyle: 0,
    lineThickness: 0.1,
    useHtmlProps: true,
  },
  fontSize: 12,
  layoutType: 'verticalLayout',
  showOnAnswersReport: false,
  requireManualGrading: false,
  showLabel: false,
  multipleSelection: false,
  randomize: false,
  showNumbering: false,
  mcqItems: [
    {
      nodes: [
        {
          style: {},
          children: [],
          alt: '',
          height: 0,
          href: '',
          src: '',
          tag: 'p',
          target: '',
          text: 'winter',
          width: 0,
        },
      ],
      scoreValue: 0,
    },
    {
      nodes: [
        {
          style: {},
          children: [],
          alt: '',
          height: 0,
          href: '',
          src: '',
          tag: 'p',
          target: '',
          text: 'spring',
          width: 0,
        },
      ],
      scoreValue: 0,
    },
    {
      nodes: [
        {
          style: {},
          children: [],
          alt: '',
          height: 0,
          href: '',
          src: '',
          tag: 'p',
          target: '',
          text: 'summer',
          width: 0,
        },
      ],
      scoreValue: 0,
    },
    {
      nodes: [
        {
          style: {},
          children: [],
          alt: '',
          height: 0,
          href: '',
          src: '',
          tag: 'p',
          target: '',
          text: 'fall',
          width: 0,
        },
      ],
      scoreValue: 0,
    },
  ],
  enabled: true,
  $schema: '',
  borderAlpha: 0,
  borderColor: 0,
  customCssClass: '',
  height: 100,
  maxManualGrade: 0,
  verticalGap: 0,
  width: 471,
  x: 510,
  y: 130,
  z: 0,
};
