apiVersion: v1
kind: LimitRange
metadata:
  name: preview-default-limits
  namespace: {{PR_NAMESPACE}}
spec:
  limits:
    - type: Container
      defaultRequest:
        cpu: 200m
        memory: 512Mi
      default:
        cpu: 500m
        memory: 1Gi
      max:
        cpu: "1"
        memory: 2Gi
