apiVersion: v1
kind: ResourceQuota
metadata:
  name: preview-quota
  namespace: {{PR_NAMESPACE}}
spec:
  hard:
    requests.cpu: "1000m"
    requests.memory: 2Gi
    limits.cpu: "2000m"
    limits.memory: 4Gi
    persistentvolumeclaims: "2"
    requests.storage: 10Gi
