export const LEARNING_LANGUAGES_TYPE = {
  ab: { value: 'ab', visible: 'Abkhaz [ab]' },
  aa: { value: 'aa', visible: 'Afar [aa]' },
  af: { value: 'af', visible: 'Afrikaans [af]' },
  ak: { value: 'ak', visible: 'Akan [ak]' },
  sq: { value: 'sq', visible: 'Albanian [sq]' },
  am: { value: 'am', visible: 'Amharic [am]' },
  ar: { value: 'ar', visible: 'Arabic [ar]' },
  an: { value: 'an', visible: 'Aragonese [an]' },
  hy: { value: 'hy', visible: 'Armenian [hy]' },
  as: { value: 'as', visible: 'Assamese [as]' },
  av: { value: 'av', visible: 'Avaric [av]' },
  ae: { value: 'ae', visible: 'Avestan [ae]' },
  ay: { value: 'ay', visible: 'Aymara [ay]' },
  az: { value: 'az', visible: 'Azerbaijani [az]' },
  bm: { value: 'bm', visible: 'Bambara [bm]' },
  ba: { value: 'ba', visible: 'Bashkir [ba]' },
  eu: { value: 'eu', visible: 'Basque [eu]' },
  be: { value: 'be', visible: 'Belarusian [be]' },
  bn: { value: 'bn', visible: 'Bengali [bn]' },
  bh: { value: 'bh', visible: 'Bihari [bh]' },
  bi: { value: 'bi', visible: 'Bislama [bi]' },
  bs: { value: 'bs', visible: 'Bosnian [bs]' },
  br: { value: 'br', visible: 'Breton [br]' },
  bg: { value: 'bg', visible: 'Bulgarian [bg]' },
  my: { value: 'my', visible: 'Burmese [my]' },
  ca: { value: 'ca', visible: 'Catalan; Valencian [ca]' },
  ch: { value: 'ch', visible: 'Chamorro [ch]' },
  ce: { value: 'ce', visible: 'Chechen [ce]' },
  ny: { value: 'ny', visible: 'Chichewa; Chewa; Nyanja [ny]' },
  zh: { value: 'zh', visible: 'Chinese [zh]' },
  cv: { value: 'cv', visible: 'Chuvash [cv]' },
  kw: { value: 'kw', visible: 'Cornish [kw]' },
  co: { value: 'co', visible: 'Corsican [co]' },
  cr: { value: 'cr', visible: 'Cree [cr]' },
  hr: { value: 'hr', visible: 'Croatian [hr]' },
  cs: { value: 'cs', visible: 'Czech [cs]' },
  da: { value: 'da', visible: 'Danish [da]' },
  dv: { value: 'dv', visible: 'Divehi; Dhivehi; Maldivian; [dv]' },
  nl: { value: 'nl', visible: 'Dutch [nl]' },
  en: { value: 'en', visible: 'English [en]' },
  eo: { value: 'eo', visible: 'Esperanto [eo]' },
  et: { value: 'et', visible: 'Estonian [et]' },
  ee: { value: 'ee', visible: 'Ewe [ee]' },
  fo: { value: 'fo', visible: 'Faroese [fo]' },
  fj: { value: 'fj', visible: 'Fijian [fj]' },
  fi: { value: 'fi', visible: 'Finnish [fi]' },
  fr: { value: 'fr', visible: 'French [fr]' },
  ff: { value: 'ff', visible: 'Fula; Fulah; Pulaar; Pular [ff]' },
  gl: { value: 'gl', visible: 'Galician [gl]' },
  ka: { value: 'ka', visible: 'Georgian [ka]' },
  de: { value: 'de', visible: 'German [de]' },
  el: { value: 'el', visible: 'Greek, Modern [el]' },
  gn: { value: 'gn', visible: 'Guaraní [gn]' },
  gu: { value: 'gu', visible: 'Gujarati [gu]' },
  ht: { value: 'ht', visible: 'Haitian; Haitian Creole [ht]' },
  ha: { value: 'ha', visible: 'Hausa [ha]' },
  he: { value: 'he', visible: 'Hebrew (modern) [he]' },
  hz: { value: 'hz', visible: 'Herero [hz]' },
  hi: { value: 'hi', visible: 'Hindi [hi]' },
  ho: { value: 'ho', visible: 'Hiri Motu [ho]' },
  hu: { value: 'hu', visible: 'Hungarian [hu]' },
  ia: { value: 'ia', visible: 'Interlingua [ia]' },
  id: { value: 'id', visible: 'Indonesian [id]' },
  ie: { value: 'ie', visible: 'Interlingue [ie]' },
  ga: { value: 'ga', visible: 'Irish [ga]' },
  ig: { value: 'ig', visible: 'Igbo [ig]' },
  ik: { value: 'ik', visible: 'Inupiaq [ik]' },
  io: { value: 'io', visible: 'Ido [io]' },
  is: { value: 'is', visible: 'Icelandic [is]' },
  it: { value: 'it', visible: 'Italian [it]' },
  iu: { value: 'iu', visible: 'Inuktitut [iu]' },
  ja: { value: 'ja', visible: 'Japanese [ja]' },
  jv: { value: 'jv', visible: 'Javanese [jv]' },
  kl: { value: 'kl', visible: 'Kalaallisut, Greenlandic [kl]' },
  kn: { value: 'kn', visible: 'Kannada [kn]' },
  kr: { value: 'kr', visible: 'Kanuri [kr]' },
  ks: { value: 'ks', visible: 'Kashmiri [ks]' },
  kk: { value: 'kk', visible: 'Kazakh [kk]' },
  km: { value: 'km', visible: 'Khmer [km]' },
  ki: { value: 'ki', visible: 'Kikuyu, Gikuyu [ki]' },
  rw: { value: 'rw', visible: 'Kinyarwanda [rw]' },
  ky: { value: 'ky', visible: 'Kirghiz, Kyrgyz [ky]' },
  kv: { value: 'kv', visible: 'Komi [kv]' },
  kg: { value: 'kg', visible: 'Kongo [kg]' },
  ko: { value: 'ko', visible: 'Korean [ko]' },
  ku: { value: 'ku', visible: 'Kurdish [ku]' },
  kj: { value: 'kj', visible: 'Kwanyama, Kuanyama [kj]' },
  la: { value: 'la', visible: 'Latin [la]' },
  lb: { value: 'lb', visible: 'Luxembourgish, Letzeburgesch [lb]' },
  lg: { value: 'lg', visible: 'Luganda [lg]' },
  li: { value: 'li', visible: 'Limburgish, Limburgan, Limburger [li]' },
  ln: { value: 'ln', visible: 'Lingala [ln]' },
  lo: { value: 'lo', visible: 'Lao [lo]' },
  lt: { value: 'lt', visible: 'Lithuanian [lt]' },
  lu: { value: 'lu', visible: 'Luba-Katanga [lu]' },
  lv: { value: 'lv', visible: 'Latvian [lv]' },
  gv: { value: 'gv', visible: 'Manx [gv]' },
  mk: { value: 'mk', visible: 'Macedonian [mk]' },
  mg: { value: 'mg', visible: 'Malagasy [mg]' },
  ms: { value: 'ms', visible: 'Malay [ms]' },
  ml: { value: 'ml', visible: 'Malayalam [ml]' },
  mt: { value: 'mt', visible: 'Maltese [mt]' },
  mi: { value: 'mi', visible: 'Māori [mi]' },
  mr: { value: 'mr', visible: 'Marathi (Marāṭhī) [mr]' },
  mh: { value: 'mh', visible: 'Marshallese [mh]' },
  mn: { value: 'mn', visible: 'Mongolian [mn]' },
  na: { value: 'na', visible: 'Nauru [na]' },
  nv: { value: 'nv', visible: 'Navajo, Navaho [nv]' },
  nb: { value: 'nb', visible: 'Norwegian Bokmål [nb]' },
  nd: { value: 'nd', visible: 'North Ndebele [nd]' },
  ne: { value: 'ne', visible: 'Nepali [ne]' },
  ng: { value: 'ng', visible: 'Ndonga [ng]' },
  nn: { value: 'nn', visible: 'Norwegian Nynorsk [nn]' },
  no: { value: 'no', visible: 'Norwegian [no]' },
  ii: { value: 'ii', visible: 'Nuosu [ii]' },
  nr: { value: 'nr', visible: 'South Ndebele [nr]' },
  oc: { value: 'oc', visible: 'Occitan [oc]' },
  oj: { value: 'oj', visible: 'Ojibwe, Ojibwa [oj]' },
  cu: {
    value: 'cu',
    visible:
      'Old Church Slavonic, Church Slavic, Church Slavonic, Old Bulgarian, Old Slavonic [cu]',
  },
  om: { value: 'om', visible: 'Oromo [om]' },
  or: { value: 'or', visible: 'Oriya [or]' },
  os: { value: 'os', visible: 'Ossetian, Ossetic [os]' },
  pa: { value: 'pa', visible: 'Panjabi, Punjabi [pa]' },
  pi: { value: 'pi', visible: 'Pāli [pi]' },
  fa: { value: 'fa', visible: 'Persian [fa]' },
  pl: { value: 'pl', visible: 'Polish [pl]' },
  ps: { value: 'ps', visible: 'Pashto, Pushto [ps]' },
  pt: { value: 'pt', visible: 'Portuguese [pt]' },
  qu: { value: 'qu', visible: 'Quechua [qu]' },
  rm: { value: 'rm', visible: 'Romansh [rm]' },
  rn: { value: 'rn', visible: 'Kirundi [rn]' },
  ro: { value: 'ro', visible: 'Romanian, Moldavian, Moldovan [ro]' },
  ru: { value: 'ru', visible: 'Russian [ru]' },
  sa: { value: 'sa', visible: 'Sanskrit (Saṁskṛta) [sa]' },
  sc: { value: 'sc', visible: 'Sardinian [sc]' },
  sd: { value: 'sd', visible: 'Sindhi [sd]' },
  se: { value: 'se', visible: 'Northern Sami [se]' },
  sm: { value: 'sm', visible: 'Samoan [sm]' },
  sg: { value: 'sg', visible: 'Sango [sg]' },
  sr: { value: 'sr', visible: 'Serbian [sr]' },
  gd: { value: 'gd', visible: 'Scottish Gaelic; Gaelic [gd]' },
  sn: { value: 'sn', visible: 'Shona [sn]' },
  si: { value: 'si', visible: 'Sinhala, Sinhalese [si]' },
  sk: { value: 'sk', visible: 'Slovak [sk]' },
  sl: { value: 'sl', visible: 'Slovene [sl]' },
  so: { value: 'so', visible: 'Somali [so]' },
  st: { value: 'st', visible: 'Southern Sotho [st]' },
  es: { value: 'es', visible: 'Spanish; Castilian [es]' },
  su: { value: 'su', visible: 'Sundanese [su]' },
  sw: { value: 'sw', visible: 'Swahili [sw]' },
  ss: { value: 'ss', visible: 'Swati [ss]' },
  sv: { value: 'sv', visible: 'Swedish [sv]' },
  ta: { value: 'ta', visible: 'Tamil [ta]' },
  te: { value: 'te', visible: 'Telugu [te]' },
  tg: { value: 'tg', visible: 'Tajik [tg]' },
  th: { value: 'th', visible: 'Thai [th]' },
  ti: { value: 'ti', visible: 'Tigrinya [ti]' },
  bo: { value: 'bo', visible: 'Tibetan Standard, Tibetan, Central [bo]' },
  tk: { value: 'tk', visible: 'Turkmen [tk]' },
  tl: { value: 'tl', visible: 'Tagalog [tl]' },
  tn: { value: 'tn', visible: 'Tswana [tn]' },
  to: { value: 'to', visible: 'Tonga (Tonga Islands) [to]' },
  tr: { value: 'tr', visible: 'Turkish [tr]' },
  ts: { value: 'ts', visible: 'Tsonga [ts]' },
  tt: { value: 'tt', visible: 'Tatar [tt]' },
  tw: { value: 'tw', visible: 'Twi [tw]' },
  ty: { value: 'ty', visible: 'Tahitian [ty]' },
  ug: { value: 'ug', visible: 'Uighur, Uyghur [ug]' },
  uk: { value: 'uk', visible: 'Ukrainian [uk]' },
  ur: { value: 'ur', visible: 'Urdu [ur]' },
  uz: { value: 'uz', visible: 'Uzbek [uz]' },
  ve: { value: 've', visible: 'Venda [ve]' },
  vi: { value: 'vi', visible: 'Vietnamese [vi]' },
  vo: { value: 'vo', visible: 'Volapük [vo]' },
  wa: { value: 'wa', visible: 'Walloon [wa]' },
  cy: { value: 'cy', visible: 'Welsh [cy]' },
  wo: { value: 'wo', visible: 'Wolof [wo]' },
  fy: { value: 'fy', visible: 'Western Frisian [fy]' },
  xh: { value: 'xh', visible: 'Xhosa [xh]' },
  yi: { value: 'yi', visible: 'Yiddish [yi]' },
  yo: { value: 'yo', visible: 'Yoruba [yo]' },
  za: { value: 'za', visible: 'Zhuang, Chuang [za]' },
} as const;

export type LearningLanguageType = keyof typeof LEARNING_LANGUAGES_TYPE;

export const LICENSE_OPTIONS = {
  none: { value: 'none', visible: 'Non-CC / Copyrighted / Other' },
  custom: { value: 'custom', visible: 'Custom' },
  cc_by: { value: 'cc_by', visible: 'CC BY: Attribution' },
  cc_by_sa: { value: 'cc_by_sa', visible: 'CC BY-SA: Attribution-ShareAlike' },
  cc_by_nd: { value: 'cc_by_nd', visible: 'CC BY-ND: Attribution-NoDerivatives' },
  cc_by_nc: { value: 'cc_by_nc', visible: 'CC BY-NC: Attribution-NonCommercial' },
  cc_by_nc_sa: {
    value: 'cc_by_nc_sa',
    visible: 'CC BY-NC-SA: Attribution-NonCommercial-ShareAlike',
  },
  cc_by_nc_nd: {
    value: 'cc_by_nc_nd',
    visible: 'CC BY-NC-ND: Attribution-NonCommercial-NoDerivatives',
  },
} as const;

export type LicenseOptionType = keyof typeof LICENSE_OPTIONS;
