export const TYPE_TOOLBAR = [
  'Bold',
  'Italic',
  'Code',
  'Link (⌘L)',
  'Underline',
  'Strikethrough',
  'Subscript',
  'Double Subscript',
  'Superscript',
  'Term',
  'Deemphasis',
  'Cite',
  'Foreign',
  'Popup Content',
  'Image (Inline)',
  'Formula (Inline)',
  'Callout',
  'Command Button',
  'More',
  'Format',
  'List',
  'Bulleted List',
  'Numbered List',
  'Decrease Indent',
  'Increase Indent',
  'Bullet Style',
  'No Bullet',
  'Disc',
  'Circle',
  'Square',
  'No Bullet',
  'Decimal - 1',
  'Zero Decimal - 01',
  'Lower Roman - i',
  'Upper Roman - I',
  'Lower Alpha - a',
  'Upper Alpha - A',
  'Heading',
  'Heading 1',
  'Heading 2',
  'Insert Table',
  'Insert Image',
  'YouTube',
  'Insert...',
  'Video',
  'Audio Clip',
  'Webpage',
  'Code (Block)',
  'Formula',
  'Figure',
  'Theorem',
  'Callout',
  'Page Link',
  'Description List',
  'Definition',
  'Dialog',
  'Conjugation',
  'Switch to Markdown editor',
  'Change To  Right-to-Left  text direction',
  'Change To  Left-to-Right  text direction',
  'Undo',
  'Redo',
] as const;

export type TypeToolbar = (typeof TYPE_TOOLBAR)[number];
