import { test } from '@fixture/my-fixture';
import { TestData } from '../test-data';
import { TYPE_ACTIVITY, TypeActivity } from '@pom/types/type-activity';

const testData = new TestData();
const questionText = 'Question test?';

test.describe('Course authoring', () => {
  test('Log in as an author and create a new course project with valid details, set the Publishing Visibility as Open', async ({
    homeTask,
    projectTask,
    curriculumTask,
    utils,
  }) => {
    const startDate = new Date();
    const endDate = new Date();
    endDate.setFullYear(endDate.getFullYear() + 1);

    await homeTask.login('author');
    const projectNameFilter = await projectTask.filterAndReturnProject(testData.projectNameFilter);
    const projectNameID = utils.incrementID(projectNameFilter);
    const { projectName, projectID } = await projectTask.createNewProjectAsOpen(projectNameID);
    await homeTask.enterToPublish();
    await projectTask.publishProject();
    await homeTask.logout();
    await homeTask.login('instructor');
    await curriculumTask.createCourseFromProject(
      projectName,
      projectID,
      startDate,
      endDate,
      testData.baseUrl,
    );
  });

  test('Edit project attributes language and license with valid details', async ({
    homeTask,
    projectTask,
  }) => {
    const projectName = 'TQA-10-automation';
    const languageValue = 'belarusian';
    const licenseValue = 'cc_by';

    await homeTask.login('author');
    await projectTask.searchAndEnterProject(projectName);
    await projectTask.configureProjectAttributes(languageValue, licenseValue);
  });

  test.describe('Enable and verify one activity per test', () => {
    const projectName = 'TQA-11-automation';
    const activities: TypeActivity[] = [
      'logic_lab',
      'adaptive',
      'dnd',
      'dd',
      'coding',
      'file_aupload',
      'hotspot',
      'likert',
      'multi',
      'embed',
      'response_multi',
      'vlab',
    ];

    for (const activity of activities) {
      const label = TYPE_ACTIVITY[activity].label;
      test(`Activity: ${label}`, async ({ homeTask, curriculumTask, projectTask }) => {
        await homeTask.login('author');
        await projectTask.searchAndEnterProject(projectName);
        await curriculumTask.setActivityState(activity, 'Enable');
        await homeTask.enterToCurriculum();
        await curriculumTask.addPageAndEnter('basic-practice');
        await curriculumTask.addQuestionActivity(activity);
        await homeTask.enterToCourseAuthor();
        await projectTask.searchAndEnterProject(projectName);
        await homeTask.enterToCurriculum();
        await curriculumTask.deletePage();
        await homeTask.enterToOverview();
        await curriculumTask.setActivityState(activity, 'Disable');
      });
    }
  });

  test('Modify text, add an image, and change text formatting in an BASIC page', async ({
    homeTask,
    projectTask,
    curriculumTask,
  }) => {
    const projectName = 'TQA-12-automation';
    const paragraphText = 'Text generated by automation';
    const newParagraphText = 'New text generated by automation';
    const imageFileName = 'img-mock-05-16-2025.jpg';

    await homeTask.login('author');
    await projectTask.searchAndEnterProject(projectName);
    await homeTask.enterToCurriculum();
    await curriculumTask.addPageAndEnter('basic-practice');
    await curriculumTask.fillOnParagraphAndSelectContent(paragraphText);
    await curriculumTask.addQuestionActivity('paragraph');
    await curriculumTask.fillOnParagraphAndSelectContent(newParagraphText, 0, 'Format', 'List');
    await curriculumTask.waitChangeVisualize(newParagraphText, paragraphText);
    await curriculumTask.addQuestionActivity('paragraph');
    await curriculumTask.clickOnParagraphAndSelectContent(0, 'Insert Image');
    await curriculumTask.selectMediaFile('image', imageFileName);
    await curriculumTask.waitChangeVisualizeMedia(imageFileName, 'img');
    await homeTask.enterToCurriculum();
    await curriculumTask.deletePage();
  });

  test.describe('Add one of each type of content to a new page', () => {
    const projectName = 'TQA-13-automation';
    const typePage = 'basic-practice';

    test.beforeEach(async ({ homeTask, curriculumTask, projectTask: taskProject }) => {
      await homeTask.login('author');
      await taskProject.searchAndEnterProject(projectName);
      await homeTask.enterToCurriculum();
      await curriculumTask.addPageAndEnter(typePage);
    });

    test.afterEach(async ({ homeTask, curriculumTask, projectTask }) => {
      await homeTask.enterToCourseAuthor();
      await projectTask.searchAndEnterProject(projectName);
      await homeTask.enterToCurriculum();
      await curriculumTask.deletePage();
    });

    test('Content: Cite', async ({ curriculumTask }) => {
      const citation = {
        name: 'Newton, I.',
        text: 'Newton, I. (2015). Philosophiae Naturalis Principia Mathematica (Latin,1687). Benediction Classics.',
      };

      await curriculumTask.addCiteToolbar(citation.name, citation.text);
    });

    test('Content: Foreign', async ({ curriculumTask }) => {
      const language = 'arabic';
      const paragraphText = 'Text generated by automation';

      await curriculumTask.addForeignToolbar(paragraphText, language);
    });

    test('Content: Image', async ({ curriculumTask }) => {
      const imageName = 'img-mock-05-16-2025.jpg';

      await curriculumTask.addImageToolbar(imageName);
    });

    test('Content: Formula', async ({ curriculumTask }) => {
      const formula = '1+2=3';

      await curriculumTask.addFormulaToolbar(formula);
    });

    test('Content: Callout', async ({ curriculumTask }) => {
      const paragraphText =
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.';

      await curriculumTask.addCalloutToolbar(paragraphText);
    });

    test('Content: PopUp', async ({ curriculumTask }) => {
      const paragraphText = 'Text generated by automation';
      const popupText = 'Popup text';

      await curriculumTask.addPopUpToolbar(paragraphText, popupText);
    });

    test('Content: Dialog', async ({ curriculumTask }) => {
      const dialogTitle = "This is a dialog's title";
      const dialogSpeaker = 'Leonardo';
      const dialogContent = 'This is my text';

      await curriculumTask.addDialogToolbar(dialogTitle, dialogSpeaker, dialogContent);
    });

    test('Content: Table', async ({ curriculumTask }) => {
      const tableCaption = 'My table Caption';
      const tableData = {
        c1: 'My cell 1',
        c2: 'My cell 2',
      };

      await curriculumTask.addTableToolbar(tableCaption, tableData.c1, tableData.c2);
    });

    test('Content: Theorem', async ({ curriculumTask }) => {
      const title = 'Theorem Title';

      await curriculumTask.addTheoremToolbar(title);
    });

    test('Content: Conjugation', async ({ curriculumTask }) => {
      const dataTable = {
        headColumn1: 'Singular',
        headColumn2: 'Plural',
        headRow1: '1st Person',
        headRow2: '2nd Person',
        headRow3: '3rd Person',
      };

      await curriculumTask.addConjugationToolbar(
        dataTable.headColumn1,
        dataTable.headColumn2,
        dataTable.headRow1,
        dataTable.headRow2,
        dataTable.headRow3,
      );
    });

    test('Content: Description List', async ({ curriculumTask }) => {
      const title = 'My title';
      const term = 'My term';
      const definition = 'My definition';

      await curriculumTask.addDescriptionListToolbar(title, term, definition);
    });

    test('Content: Audio clip', async ({ curriculumTask }) => {
      const audioFileName = 'audio-test-01.mp3';
      const audioCaption = 'My Audio Caption';

      await curriculumTask.addAudioClipToolbar(audioFileName, audioCaption);
    });

    test('Content: Video', async ({ curriculumTask }) => {
      const videoFileName = 'video-test-01.mp4';

      await curriculumTask.addVideoToolbar(videoFileName);
    });

    test('Content: Insert YouTube', async ({ curriculumTask }) => {
      const youtubeUrl = 'https://www.youtube.com/watch?v=2QAMzupR_C4';
      const youtubeId = '2QAMzupR_C4';

      await curriculumTask.addYoutubeToolbar(youtubeUrl, youtubeId);
    });

    test('Content: Web page', async ({ curriculumTask }) => {
      const webPageUrl = 'https://es.wikipedia.org/wiki/Wikipedia:Portada';

      await curriculumTask.addWebPageToolbar(webPageUrl);
    });

    test('Content: Code block', async ({ curriculumTask }) => {
      const codeType = 'python';
      const code = 'print("Hola, mundo!")';
      const caption = 'Test Code block';

      await curriculumTask.addCodeBlockToolbar(codeType, code, caption);
    });

    test('Content: Figure', async ({ curriculumTask }) => {
      const title = 'Test Figure Title';

      await curriculumTask.addFigureToolbar(title);
    });

    test('Content: Page link', async ({ curriculumTask }) => {
      const pageName = 'New Page';

      await curriculumTask.addPageLinkToolbar(pageName);
    });

    test('Content: Definition', async ({ curriculumTask }) => {
      const term = 'Algorithm';
      const description =
        'A set of rules or instructions that specify how to solve a problem or perform a task';

      await curriculumTask.addDefinitionToolbar(term, description);
    });
  });

  test.describe('Add an ungraded page to the curriculum, add at least one type of each activity and edit them', () => {
    const projectName = 'TQA-14-automation';

    test.beforeEach(async ({ homeTask, curriculumTask, projectTask }) => {
      await homeTask.login('author');
      await projectTask.searchAndEnterProject(projectName);
      await homeTask.enterToCurriculum();
      await curriculumTask.addPageAndEnter('basic-practice');
    });

    test.afterEach(async ({ homeTask, curriculumTask }) => {
      await homeTask.enterToCurriculum();
      await curriculumTask.deletePage();
    });

    test('Activity: CATA', async ({ curriculumTask }) => {
      await curriculumTask.addActivitiesWithQuestions('Check All That Apply', 'cata', questionText);
    });

    test('Activity: MCQ', async ({ curriculumTask }) => {
      await curriculumTask.addActivitiesWithQuestions('Multiple Choice', 'mcq', questionText);
    });

    test('Activity: Order', async ({ curriculumTask }) => {
      await curriculumTask.addActivitiesWithQuestions('Ordering', 'order', questionText);
    });

    test('Activity: Input', async ({ curriculumTask }) => {
      await curriculumTask.addActivitiesWithQuestions('Single Response', 'input', questionText);
    });
  });

  test.describe('Add an graded page to the curriculum, add at least one type of each activity and edit them', () => {
    const projectName = 'TQA-15-automation';

    test.beforeEach(async ({ homeTask, curriculumTask, projectTask }) => {
      await homeTask.login('author');
      await projectTask.searchAndEnterProject(projectName);
      await homeTask.enterToCurriculum();
      await curriculumTask.addPageAndEnter('basic-scored', 'New Assessment');
    });

    test.afterEach(async ({ curriculumTask }) => {
      await curriculumTask.waitChangeVisualize(questionText);
    });

    test.afterEach(async ({ homeTask, curriculumTask }) => {
      await homeTask.enterToCurriculum();
      await curriculumTask.deletePage('New Assessment');
    });

    test('Activity: Vlab', async ({ curriculumTask }) => {
      await curriculumTask.addActivityVlab(questionText);
    });

    test('Activity: DD', async ({ curriculumTask }) => {
      await curriculumTask.buildQuestionActivity('Directed Discussion', 'dd', questionText);
    });

    test('Activity: Response Multi', async ({ curriculumTask }) => {
      await curriculumTask.addActivityResponseMulti(questionText);
    });

    test('Activity: Multi', async ({ curriculumTask }) => {
      await curriculumTask.addActivityMulti(questionText);
    });

    test('Activity: Likert', async ({ curriculumTask }) => {
      await curriculumTask.addActivityLikert(questionText);
    });

    test('Activity: DnD', async ({ curriculumTask }) => {
      await curriculumTask.buildQuestionActivity('Custom Drag and Drop', 'dnd', questionText);
    });

    test('Activity: Upload', async ({ curriculumTask }) => {
      await curriculumTask.buildQuestionActivity('File Upload', 'file_aupload', questionText);
    });

    test('Activity: Coding', async ({ curriculumTask }) => {
      await curriculumTask.buildQuestionActivity('Image Coding', 'coding', questionText);
    });

    test('Activity: Hotspot', async ({ curriculumTask }) => {
      await curriculumTask.addActivityHotspot(questionText);
    });
  });

  test('Add units and modules to the curriculum of a project, then add pages inside those containers', async ({
    homeTask,
    projectTask,
    curriculumTask,
  }) => {
    const projectName = 'TQA-17-automation';

    await homeTask.login('author');
    await projectTask.searchAndEnterProject(projectName);
    await homeTask.enterToCurriculum();
    await curriculumTask.addPageAndEnter('unit');
    await curriculumTask.addPage('module');
    await curriculumTask.addPage('basic-practice');
    await curriculumTask.enterPage('module', null, 'Module 1: Module', 'last');
    await curriculumTask.addPageAndEnter('basic-practice');
  });

  test('Publish project as admin and create section as instructor', async ({
    homeTask,
    projectTask,
    curriculumTask,
    utils,
  }) => {
    const startDate = new Date();
    const endDate = new Date();
    endDate.setFullYear(endDate.getFullYear() + 1);

    await homeTask.login('administrator');
    const projectNameFilter = await projectTask.filterAndReturnProject(testData.projectNameFilter);
    const projectNameID = utils.incrementID(projectNameFilter);
    const { projectName, projectID } = await projectTask.createNewProjectAsOpen(projectNameID);
    await homeTask.enterToPublish();
    await projectTask.publishProject();
    await homeTask.logout();
    await homeTask.login('instructor');
    await curriculumTask.createCourseFromProject(
      projectName,
      projectID,
      startDate,
      endDate,
      testData.baseUrl,
    );
  });

  test('Publish updates to a project with the auto-publishing checkbox checked. Then log in as a student pick the section created from the project, go to Learn, and verify that the changes appear', async ({
    homeTask,
    curriculumTask,
    projectTask,
    studentTask,
  }) => {
    const projectName = 'TQA-19-automation';
    const pageName = ['New Page', 'New Assessment', 'New Adaptive Page'];
    const description = 'New version of the project';

    await homeTask.login('author');
    await projectTask.searchAndEnterProject(projectName);
    await homeTask.enterToCurriculum();
    await curriculumTask.addPage('basic-practice');
    await curriculumTask.addPage('basic-scored');
    await curriculumTask.addPage('adaptive-practice');
    await homeTask.enterToPublish();
    await projectTask.publishProject(description);
    await homeTask.logout();
    await homeTask.login('student');
    await studentTask.searchProject(projectName);
    await homeTask.enterToLearn();
    await studentTask.validateResource(pageName);
  });

  test('Publish project and create product as instructor', async ({
    page,
    homeTask,
    projectTask,
    curriculumTask,
    utils,
  }) => {
    const startDate = new Date();
    const endDate = new Date();
    endDate.setFullYear(startDate.getFullYear() + 1);

    await homeTask.login('administrator');
    const projectNameFilter = await projectTask.filterAndReturnProject(testData.projectNameFilter);
    const projectNameID = utils.incrementID(projectNameFilter);
    const { projectName } = await projectTask.createNewProjectAsOpen(projectNameID);
    await homeTask.enterToPublish();
    await projectTask.publishProject();
    await homeTask.enterToProducts();
    const { productName } = await projectTask.createAndOpenProduct(projectName);
    await homeTask.logout();
    await homeTask.login('instructor');
    await curriculumTask.createCourseFromProduct(productName, startDate, endDate, testData.baseUrl);
  });
});
