defmodule Oli.Predefined do
  def timezones do
    [
      {"(GMT-12:00) International Date Line West", "Etc/GMT+12"},
      {"(GMT-11:00) Midway Island, Samoa", "Pacific/Midway"},
      {"(GMT-10:00) Hawaii", "Pacific/Honolulu"},
      {"(GMT-09:00) Alaska", "US/Alaska"},
      {"(GMT-08:00) Pacific Time (US & Canada)", "America/Los_Angeles"},
      {"(GMT-08:00) Tijuana, Baja California", "America/Tijuana"},
      {"(GMT-07:00) Arizona", "US/Arizona"},
      {"(GMT-07:00) Chihuahua, La Paz, Mazatlan", "America/Chihuahua"},
      {"(GMT-07:00) Mountain Time (US & Canada)", "US/Mountain"},
      {"(GMT-06:00) Central America", "America/Managua"},
      {"(GMT-06:00) Central Time (US & Canada)", "US/Central"},
      {"(GMT-06:00) Guadalajara, Mexico City, Monterrey", "America/Mexico_City"},
      {"(GMT-06:00) Saskatchewan", "Canada/Saskatchewan"},
      {"(GMT-05:00) Bogota, Lima, Quito, Rio Branco", "America/Bogota"},
      {"(GMT-05:00) Eastern Time (US & Canada)", "US/Eastern"},
      {"(GMT-05:00) Indiana (East)", "US/East-Indiana"},
      {"(GMT-04:00) Atlantic Time (Canada)", "Canada/Atlantic"},
      {"(GMT-04:00) Caracas, La Paz", "America/Caracas"},
      {"(GMT-04:00) Manaus", "America/Manaus"},
      {"(GMT-04:00) Santiago", "America/Santiago"},
      {"(GMT-03:30) Newfoundland", "Canada/Newfoundland"},
      {"(GMT-03:00) Brasilia", "America/Sao_Paulo"},
      {"(GMT-03:00) Buenos Aires, Georgetown", "America/Argentina/Buenos_Aires"},
      {"(GMT-03:00) Greenland", "America/Godthab"},
      {"(GMT-03:00) Montevideo", "America/Montevideo"},
      {"(GMT-02:00) Mid-Atlantic", "America/Noronha"},
      {"(GMT-01:00) Cape Verde Is.", "Atlantic/Cape_Verde"},
      {"(GMT-01:00) Azores", "Atlantic/Azores"},
      {"(GMT+00:00) Casablanca, Monrovia, Reykjavik", "Africa/Casablanca"},
      {"(GMT+00:00) Greenwich Mean Time : Dublin, Edinburgh, Lisbon, London", "Etc/Greenwich"},
      {"(GMT+01:00) Amsterdam, Berlin, Bern, Rome, Stockholm, Vienna", "Europe/Amsterdam"},
      {"(GMT+01:00) Belgrade, Bratislava, Budapest, Ljubljana, Prague", "Europe/Belgrade"},
      {"(GMT+01:00) Brussels, Copenhagen, Madrid, Paris", "Europe/Brussels"},
      {"(GMT+01:00) Sarajevo, Skopje, Warsaw, Zagreb", "Europe/Sarajevo"},
      {"(GMT+01:00) West Central Africa", "Africa/Lagos"},
      {"(GMT+02:00) Amman", "Asia/Amman"},
      {"(GMT+02:00) Athens, Bucharest, Istanbul", "Europe/Athens"},
      {"(GMT+02:00) Beirut", "Asia/Beirut"},
      {"(GMT+02:00) Cairo", "Africa/Cairo"},
      {"(GMT+02:00) Harare, Pretoria", "Africa/Harare"},
      {"(GMT+02:00) Helsinki, Kyiv, Riga, Sofia, Tallinn, Vilnius", "Europe/Helsinki"},
      {"(GMT+02:00) Jerusalem", "Asia/Jerusalem"},
      {"(GMT+02:00) Minsk", "Europe/Minsk"},
      {"(GMT+02:00) Windhoek", "Africa/Windhoek"},
      {"(GMT+03:00) Kuwait, Riyadh, Baghdad", "Asia/Kuwait"},
      {"(GMT+03:00) Moscow, St. Petersburg, Volgograd", "Europe/Moscow"},
      {"(GMT+03:00) Nairobi", "Africa/Nairobi"},
      {"(GMT+03:00) Tbilisi", "Asia/Tbilisi"},
      {"(GMT+03:30) Tehran", "Asia/Tehran"},
      {"(GMT+04:00) Abu Dhabi, Muscat", "Asia/Muscat"},
      {"(GMT+04:00) Baku", "Asia/Baku"},
      {"(GMT+04:00) Yerevan", "Asia/Yerevan"},
      {"(GMT+04:30) Kabul", "Asia/Kabul"},
      {"(GMT+05:00) Yekaterinburg", "Asia/Yekaterinburg"},
      {"(GMT+05:00) Islamabad, Karachi, Tashkent", "Asia/Karachi"},
      {"(GMT+05:30) Chennai, Kolkata, Mumbai, New Delhi", "Asia/Calcutta"},
      {"(GMT+05:30) Sri Jayawardenapura", "Asia/Calcutta"},
      {"(GMT+05:45) Kathmandu", "Asia/Katmandu"},
      {"(GMT+06:00) Almaty, Novosibirsk", "Asia/Almaty"},
      {"(GMT+06:00) Astana, Dhaka", "Asia/Dhaka"},
      {"(GMT+06:30) Yangon (Rangoon)", "Asia/Rangoon"},
      {"(GMT+07:00) Bangkok, Hanoi, Jakarta", "Asia/Bangkok"},
      {"(GMT+07:00) Krasnoyarsk", "Asia/Krasnoyarsk"},
      {"(GMT+08:00) Beijing, Chongqing, Hong Kong, Urumqi", "Asia/Hong_Kong"},
      {"(GMT+08:00) Kuala Lumpur, Singapore", "Asia/Kuala_Lumpur"},
      {"(GMT+08:00) Irkutsk, Ulaan Bataar", "Asia/Irkutsk"},
      {"(GMT+08:00) Perth", "Australia/Perth"},
      {"(GMT+08:00) Taipei", "Asia/Taipei"},
      {"(GMT+09:00) Osaka, Sapporo, Tokyo", "Asia/Tokyo"},
      {"(GMT+09:00) Seoul", "Asia/Seoul"},
      {"(GMT+09:00) Yakutsk", "Asia/Yakutsk"},
      {"(GMT+09:30) Adelaide", "Australia/Adelaide"},
      {"(GMT+09:30) Darwin", "Australia/Darwin"},
      {"(GMT+10:00) Brisbane", "Australia/Brisbane"},
      {"(GMT+10:00) Canberra, Melbourne, Sydney", "Australia/Canberra"},
      {"(GMT+10:00) Hobart", "Australia/Hobart"},
      {"(GMT+10:00) Guam, Port Moresby", "Pacific/Guam"},
      {"(GMT+10:00) Vladivostok", "Asia/Vladivostok"},
      {"(GMT+11:00) Magadan, Solomon Is., New Caledonia", "Asia/Magadan"},
      {"(GMT+12:00) Auckland, Wellington", "Pacific/Auckland"},
      {"(GMT+12:00) Fiji, Kamchatka, Marshall Is.", "Pacific/Fiji"},
      {"(GMT+13:00) Nuku'alofa", "Pacific/Tongatapu"}
    ]
  end

  def country_codes do
    [
      {"Afghanistan", "AF"},
      {"Åland Islands", "AX"},
      {"Albania", "AL"},
      {"Algeria", "DZ"},
      {"American Samoa", "AS"},
      {"Andorra", "AD"},
      {"Angola", "AO"},
      {"Anguilla", "AI"},
      {"Antarctica", "AQ"},
      {"Antigua and Barbuda", "AG"},
      {"Argentina", "AR"},
      {"Armenia", "AM"},
      {"Aruba", "AW"},
      {"Australia", "AU"},
      {"Austria", "AT"},
      {"Azerbaijan", "AZ"},
      {"Bahamas", "BS"},
      {"Bahrain", "BH"},
      {"Bangladesh", "BD"},
      {"Barbados", "BB"},
      {"Belarus", "BY"},
      {"Belgium", "BE"},
      {"Belize", "BZ"},
      {"Benin", "BJ"},
      {"Bermuda", "BM"},
      {"Bhutan", "BT"},
      {"Bolivia, Plurinational State of", "BO"},
      {"Bonaire, Sint Eustatius and Saba", "BQ"},
      {"Bosnia and Herzegovina", "BA"},
      {"Botswana", "BW"},
      {"Bouvet Island", "BV"},
      {"Brazil", "BR"},
      {"British Indian Ocean Territory", "IO"},
      {"Brunei Darussalam", "BN"},
      {"Bulgaria", "BG"},
      {"Burkina Faso", "BF"},
      {"Burundi", "BI"},
      {"Cambodia", "KH"},
      {"Cameroon", "CM"},
      {"Canada", "CA"},
      {"Cape Verde", "CV"},
      {"Cayman Islands", "KY"},
      {"Central African Republic", "CF"},
      {"Chad", "TD"},
      {"Chile", "CL"},
      {"China", "CN"},
      {"Christmas Island", "CX"},
      {"Cocos (Keeling) Islands", "CC"},
      {"Colombia", "CO"},
      {"Comoros", "KM"},
      {"Congo", "CG"},
      {"Congo, the Democratic Republic of the", "CD"},
      {"Cook Islands", "CK"},
      {"Costa Rica", "CR"},
      {"Côte d'Ivoire", "CI"},
      {"Croatia", "HR"},
      {"Cuba", "CU"},
      {"Curaçao", "CW"},
      {"Cyprus", "CY"},
      {"Czech Republic", "CZ"},
      {"Denmark", "DK"},
      {"Djibouti", "DJ"},
      {"Dominica", "DM"},
      {"Dominican Republic", "DO"},
      {"Ecuador", "EC"},
      {"Egypt", "EG"},
      {"El Salvador", "SV"},
      {"Equatorial Guinea", "GQ"},
      {"Eritrea", "ER"},
      {"Estonia", "EE"},
      {"Ethiopia", "ET"},
      {"Falkland Islands (Malvinas)", "FK"},
      {"Faroe Islands", "FO"},
      {"Fiji", "FJ"},
      {"Finland", "FI"},
      {"France", "FR"},
      {"French Guiana", "GF"},
      {"French Polynesia", "PF"},
      {"French Southern Territories", "TF"},
      {"Gabon", "GA"},
      {"Gambia", "GM"},
      {"Georgia", "GE"},
      {"Germany", "DE"},
      {"Ghana", "GH"},
      {"Gibraltar", "GI"},
      {"Greece", "GR"},
      {"Greenland", "GL"},
      {"Grenada", "GD"},
      {"Guadeloupe", "GP"},
      {"Guam", "GU"},
      {"Guatemala", "GT"},
      {"Guernsey", "GG"},
      {"Guinea", "GN"},
      {"Guinea-Bissau", "GW"},
      {"Guyana", "GY"},
      {"Haiti", "HT"},
      {"Heard Island and McDonald Islands", "HM"},
      {"Holy See (Vatican City State)", "VA"},
      {"Honduras", "HN"},
      {"Hong Kong", "HK"},
      {"Hungary", "HU"},
      {"Iceland", "IS"},
      {"India", "IN"},
      {"Indonesia", "ID"},
      {"Iran, Islamic Republic of", "IR"},
      {"Iraq", "IQ"},
      {"Ireland", "IE"},
      {"Isle of Man", "IM"},
      {"Israel", "IL"},
      {"Italy", "IT"},
      {"Jamaica", "JM"},
      {"Japan", "JP"},
      {"Jersey", "JE"},
      {"Jordan", "JO"},
      {"Kazakhstan", "KZ"},
      {"Kenya", "KE"},
      {"Kiribati", "KI"},
      {"Korea, Democratic People's Republic of", "KP"},
      {"Korea, Republic of", "KR"},
      {"Kuwait", "KW"},
      {"Kyrgyzstan", "KG"},
      {"Lao People's Democratic Republic", "LA"},
      {"Latvia", "LV"},
      {"Lebanon", "LB"},
      {"Lesotho", "LS"},
      {"Liberia", "LR"},
      {"Libya", "LY"},
      {"Liechtenstein", "LI"},
      {"Lithuania", "LT"},
      {"Luxembourg", "LU"},
      {"Macao", "MO"},
      {"Macedonia, the former Yugoslav Republic of", "MK"},
      {"Madagascar", "MG"},
      {"Malawi", "MW"},
      {"Malaysia", "MY"},
      {"Maldives", "MV"},
      {"Mali", "ML"},
      {"Malta", "MT"},
      {"Marshall Islands", "MH"},
      {"Martinique", "MQ"},
      {"Mauritania", "MR"},
      {"Mauritius", "MU"},
      {"Mayotte", "YT"},
      {"Mexico", "MX"},
      {"Micronesia, Federated States of", "FM"},
      {"Moldova, Republic of", "MD"},
      {"Monaco", "MC"},
      {"Mongolia", "MN"},
      {"Montenegro", "ME"},
      {"Montserrat", "MS"},
      {"Morocco", "MA"},
      {"Mozambique", "MZ"},
      {"Myanmar", "MM"},
      {"Namibia", "NA"},
      {"Nauru", "NR"},
      {"Nepal", "NP"},
      {"Netherlands", "NL"},
      {"New Caledonia", "NC"},
      {"New Zealand", "NZ"},
      {"Nicaragua", "NI"},
      {"Niger", "NE"},
      {"Nigeria", "NG"},
      {"Niue", "NU"},
      {"Norfolk Island", "NF"},
      {"Northern Mariana Islands", "MP"},
      {"Norway", "NO"},
      {"Oman", "OM"},
      {"Pakistan", "PK"},
      {"Palau", "PW"},
      {"Palestinian Territory, Occupied", "PS"},
      {"Panama", "PA"},
      {"Papua New Guinea", "PG"},
      {"Paraguay", "PY"},
      {"Peru", "PE"},
      {"Philippines", "PH"},
      {"Pitcairn", "PN"},
      {"Poland", "PL"},
      {"Portugal", "PT"},
      {"Puerto Rico", "PR"},
      {"Qatar", "QA"},
      {"Réunion", "RE"},
      {"Romania", "RO"},
      {"Russian Federation", "RU"},
      {"Rwanda", "RW"},
      {"Saint Barthélemy", "BL"},
      {"Saint Helena, Ascension and Tristan da Cunha", "SH"},
      {"Saint Kitts and Nevis", "KN"},
      {"Saint Lucia", "LC"},
      {"Saint Martin (French part)", "MF"},
      {"Saint Pierre and Miquelon", "PM"},
      {"Saint Vincent and the Grenadines", "VC"},
      {"Samoa", "WS"},
      {"San Marino", "SM"},
      {"Sao Tome and Principe", "ST"},
      {"Saudi Arabia", "SA"},
      {"Senegal", "SN"},
      {"Serbia", "RS"},
      {"Seychelles", "SC"},
      {"Sierra Leone", "SL"},
      {"Singapore", "SG"},
      {"Sint Maarten (Dutch part)", "SX"},
      {"Slovakia", "SK"},
      {"Slovenia", "SI"},
      {"Solomon Islands", "SB"},
      {"Somalia", "SO"},
      {"South Africa", "ZA"},
      {"South Georgia and the South Sandwich Islands", "GS"},
      {"South Sudan", "SS"},
      {"Spain", "ES"},
      {"Sri Lanka", "LK"},
      {"Sudan", "SD"},
      {"Suriname", "SR"},
      {"Svalbard and Jan Mayen", "SJ"},
      {"Swaziland", "SZ"},
      {"Sweden", "SE"},
      {"Switzerland", "CH"},
      {"Syrian Arab Republic", "SY"},
      {"Taiwan, Province of China", "TW"},
      {"Tajikistan", "TJ"},
      {"Tanzania, United Republic of", "TZ"},
      {"Thailand", "TH"},
      {"Timor-Leste", "TL"},
      {"Togo", "TG"},
      {"Tokelau", "TK"},
      {"Tonga", "TO"},
      {"Trinidad and Tobago", "TT"},
      {"Tunisia", "TN"},
      {"Turkey", "TR"},
      {"Turkmenistan", "TM"},
      {"Turks and Caicos Islands", "TC"},
      {"Tuvalu", "TV"},
      {"Uganda", "UG"},
      {"Ukraine", "UA"},
      {"United Arab Emirates", "AE"},
      {"United Kingdom", "GB"},
      {"United States", "US"},
      {"United States Minor Outlying Islands", "UM"},
      {"Uruguay", "UY"},
      {"Uzbekistan", "UZ"},
      {"Vanuatu", "VU"},
      {"Venezuela, Bolivarian Republic of", "VE"},
      {"Viet Nam", "VN"},
      {"Virgin Islands, British", "VG"},
      {"Virgin Islands, U.S.", "VI"},
      {"Wallis and Futuna", "WF"},
      {"Western Sahara", "EH"},
      {"Yemen", "YE"},
      {"Zambia", "ZM"},
      {"Zimbabwe", "ZW"}
    ]
  end

  def world_universities_and_domains do
    Application.get_env(:oli, :world_universities_and_domains_json)
    |> Jason.decode!()
    |> Enum.map(fn el ->
      %{
        name: el["name"],
        country_code: el["alpha_two_code"],
        # pick the first webpage url in a list of possible urls for a university
        institution_url: Enum.at(el["web_pages"], 0)
      }
    end)
  end

  def lti_config_defaults do
    configs = [
      %{
        product_family_code: "canvas",
        name: "Canvas",
        key_set_path: "/api/lti/security/jwks",
        auth_token_path: "/login/oauth2/token",
        auth_login_path: "/api/lti/authorize_redirect",
        auth_server_path: "/"
      },
      %{
        product_family_code: "moodle",
        name: "Moodle",
        key_set_path: "/mod/lti/certs.php",
        auth_token_path: "/mod/lti/token.php",
        auth_login_path: "/mod/lti/auth.php",
        auth_server_path: "/"
      }
    ]

    case Application.get_env(:oli, :blackboard_application_client_id) do
      nil ->
        configs

      blackboard_application_client_id ->
        [
          %{
            product_family_code: "blackboard",
            name: "Blackboard",
            key_set_url:
              "https://developer.blackboard.com/api/v1/management/applications/#{blackboard_application_client_id}/jwks.json",
            auth_token_url: "https://developer.blackboard.com/api/v1/gateway/oauth2/jwttoken",
            auth_login_url: "https://developer.blackboard.com/api/v1/gateway/oidcauth",
            auth_server_url: "https://blackboard.com/api/lti/security/jwks"
          }
          | configs
        ]
    end
  end
end
