export const sample1 = {
  nodes: [
    {
      id: '17042',
      resourceId: 17042,
      type: 'screen',
      draggable: false,
      position: {
        x: 50,
        y: 50,
      },
      data: {
        id: 17042,
        resourceId: 17042,
        activitySlug: 'new_screen_2hyvr',
        activityType: {
          authoring_element: 'oli-adaptive-authoring',
          authoring_script: 'oli_adaptive_authoring.js',
          delivery_element: 'oli-adaptive-delivery',
          delivery_script: 'oli_adaptive_delivery.js',
          enabled: true,
          global: true,
          id: 1,
          petite_label: 'Adaptive',
          slug: 'oli_adaptive',
          title: 'Adaptive Activity',
        },
        content: {
          bibrefs: [],
          custom: {
            applyBtnFlag: false,
            applyBtnLabel: '',
            checkButtonLabel: 'Next',
            combineFeedback: false,
            customCssClass: '',
            facts: [],
            height: 600,
            lockCanvasSize: false,
            mainBtnLabel: '',
            maxAttempt: 0,
            maxScore: 0,
            negativeScoreAllowed: false,
            palette: {
              backgroundColor: 'rgba(255,255,255,0)',
              borderColor: 'rgba(255,255,255,0)',
              borderRadius: '',
              borderStyle: 'solid',
              borderWidth: '1px',
            },
            panelHeaderColor: 0,
            panelTitleColor: 0,
            showCheckBtn: true,
            trapStateScoreScheme: false,
            width: 800,
            x: 0,
            y: 0,
            z: 0,
          },
          partsLayout: [],
        },
        authoring: {
          flowchart: {
            paths: [
              {
                completed: true,
                destinationScreenId: '17044',
                id: '411416557',
                label: 'Always',
                priority: 12,
                ruleId: null,
                type: 'always-go-to',
              },
            ],
          },
          parts: [
            {
              id: '__default',
              inherited: false,
              owner: 'adaptive_activity_d3kbf_3408856619',
              type: 'janus-text-flow',
            },
          ],
          rules: [],
        },
        title: 'New Screen',
        objectives: {},
      },
    },
    {
      id: '17041',
      resourceId: 17041,
      type: 'screen',
      draggable: false,
      position: {
        x: 250,
        y: 50,
      },
      data: {
        id: 17041,
        resourceId: 17041,
        activitySlug: 'new_screen_3yq9x',
        activityType: {
          authoring_element: 'oli-adaptive-authoring',
          authoring_script: 'oli_adaptive_authoring.js',
          delivery_element: 'oli-adaptive-delivery',
          delivery_script: 'oli_adaptive_delivery.js',
          enabled: true,
          global: true,
          id: 1,
          petite_label: 'Adaptive',
          slug: 'oli_adaptive',
          title: 'Adaptive Activity',
        },
        content: {
          bibrefs: [],
          custom: {
            applyBtnFlag: false,
            applyBtnLabel: '',
            checkButtonLabel: 'Next',
            combineFeedback: false,
            customCssClass: '',
            facts: [],
            height: 600,
            lockCanvasSize: false,
            mainBtnLabel: '',
            maxAttempt: 0,
            maxScore: 0,
            negativeScoreAllowed: false,
            palette: {
              backgroundColor: 'rgba(255,255,255,0)',
              borderColor: 'rgba(255,255,255,0)',
              borderRadius: '',
              borderStyle: 'solid',
              borderWidth: '1px',
            },
            panelHeaderColor: 0,
            panelTitleColor: 0,
            showCheckBtn: true,
            trapStateScoreScheme: false,
            width: 800,
            x: 0,
            y: 0,
            z: 0,
          },
          partsLayout: [],
        },
        authoring: {
          flowchart: {
            paths: [
              {
                completed: true,
                destinationScreenId: '17043',
                id: '1638841391',
                label: 'Always',
                priority: 12,
                ruleId: null,
                type: 'always-go-to',
              },
              {
                type: 'unknown-reason-path',
                id: '501879373',
                ruleId: null,
                destinationScreenId: 17045,
                completed: false,
                label: 'Empty Rule',
                priority: 20,
              },
            ],
          },
          parts: [
            {
              id: '__default',
              inherited: false,
              owner: 'adaptive_activity_2k3xu_3670954031',
              type: 'janus-text-flow',
            },
          ],
          rules: [],
        },
        title: 'New Screen',
        objectives: {},
      },
    },
    {
      id: '17043',
      resourceId: 17043,
      type: 'screen',
      draggable: false,
      position: {
        x: 450,
        y: 50,
      },
      data: {
        id: 17043,
        resourceId: 17043,
        activitySlug: 'new_screen_rs0u6',
        activityType: {
          authoring_element: 'oli-adaptive-authoring',
          authoring_script: 'oli_adaptive_authoring.js',
          delivery_element: 'oli-adaptive-delivery',
          delivery_script: 'oli_adaptive_delivery.js',
          enabled: true,
          global: true,
          id: 1,
          petite_label: 'Adaptive',
          slug: 'oli_adaptive',
          title: 'Adaptive Activity',
        },
        content: {
          bibrefs: [],
          custom: {
            applyBtnFlag: false,
            applyBtnLabel: '',
            checkButtonLabel: 'Next',
            combineFeedback: false,
            customCssClass: '',
            facts: [],
            height: 600,
            lockCanvasSize: false,
            mainBtnLabel: '',
            maxAttempt: 0,
            maxScore: 0,
            negativeScoreAllowed: false,
            palette: {
              backgroundColor: 'rgba(255,255,255,0)',
              borderColor: 'rgba(255,255,255,0)',
              borderRadius: '',
              borderStyle: 'solid',
              borderWidth: '1px',
            },
            panelHeaderColor: 0,
            panelTitleColor: 0,
            showCheckBtn: true,
            trapStateScoreScheme: false,
            width: 800,
            x: 0,
            y: 0,
            z: 0,
          },
          partsLayout: [],
        },
        authoring: {
          flowchart: {
            paths: [
              {
                completed: true,
                destinationScreenId: '17042',
                id: '2011941876',
                label: 'Always',
                priority: 12,
                ruleId: null,
                type: 'always-go-to',
              },
              {
                type: 'unknown-reason-path',
                id: '3596859245',
                ruleId: null,
                destinationScreenId: 17044,
                completed: false,
                label: 'Empty Rule',
                priority: 20,
              },
            ],
          },
          parts: [
            {
              id: '__default',
              inherited: false,
              owner: 'adaptive_activity_go8r2_4101500156',
              type: 'janus-text-flow',
            },
          ],
          rules: [],
        },
        title: 'New Screen',
        objectives: {},
      },
    },
    {
      id: '17044',
      resourceId: 17044,
      type: 'screen',
      draggable: false,
      position: {
        x: 650,
        y: 50,
      },
      data: {
        id: 17044,
        resourceId: 17044,
        activitySlug: 'adaptive_activity_qx56t',
        activityType: {
          authoring_element: 'oli-adaptive-authoring',
          authoring_script: 'oli_adaptive_authoring.js',
          delivery_element: 'oli-adaptive-delivery',
          delivery_script: 'oli_adaptive_delivery.js',
          enabled: true,
          global: true,
          id: 1,
          petite_label: 'Adaptive',
          slug: 'oli_adaptive',
          title: 'Adaptive Activity',
        },
        content: {
          custom: {
            applyBtnFlag: false,
            applyBtnLabel: '',
            checkButtonLabel: 'Next',
            combineFeedback: false,
            customCssClass: '',
            facts: [],
            lockCanvasSize: false,
            mainBtnLabel: '',
            maxAttempt: 0,
            maxScore: 0,
            negativeScoreAllowed: false,
            palette: {
              backgroundColor: 'rgba(255,255,255,0)',
              borderColor: 'rgba(255,255,255,0)',
              borderRadius: '',
              borderStyle: 'solid',
              borderWidth: '1px',
            },
            panelHeaderColor: 0,
            panelTitleColor: 0,
            showCheckBtn: true,
            trapStateScoreScheme: false,
            width: 800,
            height: 600,
            x: 0,
            y: 0,
            z: 0,
          },
          partsLayout: [],
        },
        authoring: {
          parts: [
            {
              id: '__default',
              type: 'janus-text-flow',
              inherited: false,
              owner: 'self',
            },
          ],
          rules: [],
          flowchart: {
            paths: [
              {
                type: 'end-of-activity',
                id: '181964726',
                ruleId: null,
                completed: false,
                label: 'Exit Activity',
                priority: 16,
              },
            ],
          },
        },
        title: 'New Screen',
        tags: [],
      },
    },
    {
      id: '17045',
      resourceId: 17045,
      type: 'screen',
      draggable: false,
      position: {
        x: 850,
        y: 50,
      },
      data: {
        id: 17045,
        resourceId: 17045,
        activitySlug: 'adaptive_activity_giayz',
        activityType: {
          authoring_element: 'oli-adaptive-authoring',
          authoring_script: 'oli_adaptive_authoring.js',
          delivery_element: 'oli-adaptive-delivery',
          delivery_script: 'oli_adaptive_delivery.js',
          enabled: true,
          global: true,
          id: 1,
          petite_label: 'Adaptive',
          slug: 'oli_adaptive',
          title: 'Adaptive Activity',
        },
        content: {
          custom: {
            applyBtnFlag: false,
            applyBtnLabel: '',
            checkButtonLabel: 'Next',
            combineFeedback: false,
            customCssClass: '',
            facts: [],
            lockCanvasSize: false,
            mainBtnLabel: '',
            maxAttempt: 0,
            maxScore: 0,
            negativeScoreAllowed: false,
            palette: {
              backgroundColor: 'rgba(255,255,255,0)',
              borderColor: 'rgba(255,255,255,0)',
              borderRadius: '',
              borderStyle: 'solid',
              borderWidth: '1px',
            },
            panelHeaderColor: 0,
            panelTitleColor: 0,
            showCheckBtn: true,
            trapStateScoreScheme: false,
            width: 800,
            height: 600,
            x: 0,
            y: 0,
            z: 0,
          },
          partsLayout: [],
        },
        authoring: {
          parts: [
            {
              id: '__default',
              type: 'janus-text-flow',
              inherited: false,
              owner: 'self',
            },
          ],
          rules: [],
          flowchart: {
            paths: [
              {
                type: 'always-go-to',
                id: '1682853281',
                ruleId: null,
                destinationScreenId: 17046,
                completed: true,
                label: 'Always',
                priority: 12,
              },
              {
                type: 'unknown-reason-path',
                id: '4006861779',
                ruleId: null,
                destinationScreenId: 17047,
                completed: false,
                label: 'Empty Rule',
                priority: 20,
              },
            ],
          },
        },
        title: 'New Screen',
        tags: [],
      },
    },
    {
      id: '17046',
      resourceId: 17046,
      type: 'screen',
      draggable: false,
      position: {
        x: 1050,
        y: 50,
      },
      data: {
        id: 17046,
        resourceId: 17046,
        activitySlug: 'adaptive_activity_y33k0',
        activityType: {
          authoring_element: 'oli-adaptive-authoring',
          authoring_script: 'oli_adaptive_authoring.js',
          delivery_element: 'oli-adaptive-delivery',
          delivery_script: 'oli_adaptive_delivery.js',
          enabled: true,
          global: true,
          id: 1,
          petite_label: 'Adaptive',
          slug: 'oli_adaptive',
          title: 'Adaptive Activity',
        },
        content: {
          custom: {
            applyBtnFlag: false,
            applyBtnLabel: '',
            checkButtonLabel: 'Next',
            combineFeedback: false,
            customCssClass: '',
            facts: [],
            lockCanvasSize: false,
            mainBtnLabel: '',
            maxAttempt: 0,
            maxScore: 0,
            negativeScoreAllowed: false,
            palette: {
              backgroundColor: 'rgba(255,255,255,0)',
              borderColor: 'rgba(255,255,255,0)',
              borderRadius: '',
              borderStyle: 'solid',
              borderWidth: '1px',
            },
            panelHeaderColor: 0,
            panelTitleColor: 0,
            showCheckBtn: true,
            trapStateScoreScheme: false,
            width: 800,
            height: 600,
            x: 0,
            y: 0,
            z: 0,
          },
          partsLayout: [],
        },
        authoring: {
          parts: [
            {
              id: '__default',
              type: 'janus-text-flow',
              inherited: false,
              owner: 'self',
            },
          ],
          rules: [],
          flowchart: {
            paths: [
              {
                type: 'always-go-to',
                id: '3179857871',
                ruleId: null,
                destinationScreenId: 17048,
                completed: true,
                label: 'Always',
                priority: 12,
              },
            ],
          },
        },
        title: 'New Screen',
        tags: [],
      },
    },
    {
      id: '17047',
      resourceId: 17047,
      type: 'screen',
      draggable: false,
      position: {
        x: 1250,
        y: 50,
      },
      data: {
        id: 17047,
        resourceId: 17047,
        activitySlug: 'adaptive_activity_gih2t',
        activityType: {
          authoring_element: 'oli-adaptive-authoring',
          authoring_script: 'oli_adaptive_authoring.js',
          delivery_element: 'oli-adaptive-delivery',
          delivery_script: 'oli_adaptive_delivery.js',
          enabled: true,
          global: true,
          id: 1,
          petite_label: 'Adaptive',
          slug: 'oli_adaptive',
          title: 'Adaptive Activity',
        },
        content: {
          custom: {
            applyBtnFlag: false,
            applyBtnLabel: '',
            checkButtonLabel: 'Next',
            combineFeedback: false,
            customCssClass: '',
            facts: [],
            lockCanvasSize: false,
            mainBtnLabel: '',
            maxAttempt: 0,
            maxScore: 0,
            negativeScoreAllowed: false,
            palette: {
              backgroundColor: 'rgba(255,255,255,0)',
              borderColor: 'rgba(255,255,255,0)',
              borderRadius: '',
              borderStyle: 'solid',
              borderWidth: '1px',
            },
            panelHeaderColor: 0,
            panelTitleColor: 0,
            showCheckBtn: true,
            trapStateScoreScheme: false,
            width: 800,
            height: 600,
            x: 0,
            y: 0,
            z: 0,
          },
          partsLayout: [],
        },
        authoring: {
          parts: [
            {
              id: '__default',
              type: 'janus-text-flow',
              inherited: false,
              owner: 'self',
            },
          ],
          rules: [],
          flowchart: {
            paths: [
              {
                type: 'end-of-activity',
                id: '1252840622',
                ruleId: null,
                completed: false,
                label: 'Exit Activity',
                priority: 16,
              },
            ],
          },
        },
        title: 'New Screen',
        tags: [],
      },
    },
    {
      id: '3983038886',
      position: {
        x: 0,
        y: 0,
      },
      data: {
        fromScreenId: 17044,
      },
      draggable: false,
      type: 'placeholder',
    },
    {
      id: '3803788202',
      position: {
        x: 0,
        y: 0,
      },
      data: {
        fromScreenId: 17047,
      },
      draggable: false,
      type: 'placeholder',
    },
  ],
  edges: [
    {
      id: '411416557',
      source: '17042',
      target: '17044',
      type: 'floating',
      data: {
        completed: true,
      },
      markerEnd: {
        type: 'arrow',
        color: '#22f',
      },
    },
    {
      id: '1638841391',
      source: '17041',
      target: '17043',
      type: 'floating',
      data: {
        completed: true,
      },
      markerEnd: {
        type: 'arrow',
        color: '#22f',
      },
    },
    {
      id: '501879373',
      source: '17041',
      target: '17045',
      type: 'floating',
      data: {
        completed: false,
      },
      markerEnd: {
        type: 'arrow',
        color: '#22f',
      },
    },
    {
      id: '2011941876',
      source: '17043',
      target: '17042',
      type: 'floating',
      data: {
        completed: true,
      },
      markerEnd: {
        type: 'arrow',
        color: '#22f',
      },
    },
    {
      id: '3596859245',
      source: '17043',
      target: '17044',
      type: 'floating',
      data: {
        completed: false,
      },
      markerEnd: {
        type: 'arrow',
        color: '#22f',
      },
    },
    {
      id: '1682853281',
      source: '17045',
      target: '17046',
      type: 'floating',
      data: {
        completed: true,
      },
      markerEnd: {
        type: 'arrow',
        color: '#22f',
      },
    },
    {
      id: '4006861779',
      source: '17045',
      target: '17047',
      type: 'floating',
      data: {
        completed: false,
      },
      markerEnd: {
        type: 'arrow',
        color: '#22f',
      },
    },
    {
      id: '3179857871',
      source: '17046',
      target: '17048',
      type: 'floating',
      data: {
        completed: true,
      },
      markerEnd: {
        type: 'arrow',
        color: '#22f',
      },
    },
    {
      id: '567833552',
      source: '17044',
      target: '3983038886',
      type: 'placeholder',
      data: {
        completed: false,
      },
    },
    {
      id: '4001334374',
      source: '17047',
      target: '3803788202',
      type: 'placeholder',
      data: {
        completed: false,
      },
    },
  ],
};
