apiVersion: batch/v1
kind: Job
metadata:
  name: release-setup
spec:
  template:
    spec:
      initContainers:
        - name: patch-release-setup
          image: alpine:3.20
          command: ["sh", "-c", "exit 0"]
