name: Build amazon-linux-builder Docker Image

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Tag to use for the Docker image"
        required: true
        default: "latest"

jobs:
  build:
    name: Build amazon-linux-builder Docker Image
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: 🛎️ Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: ghcr.io/simon-initiative/amazon-linux-builder
          tags: latest,${{ github.event.inputs.tag }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=registry,ref=ghcr.io/simon-initiative/amazon-linux-builder:buildcache
          cache-to: type=registry,ref=ghcr.io/simon-initiative/amazon-linux-builder:buildcache,mode=max
