name: Build & Test Lockfile Push

on:
  push:
    paths:
      - priv_signal.lockfile.json

jobs:
  elixir-build-test:
    name: Elixir build and test
    runs-on: ubuntu-latest
    services:
      postgres:
        image: ankane/pgvector
        env:
          POSTGRES_DB: oli_test
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U postgres -d oli_test"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      MIX_ENV: test
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      DATABASE_URL: postgresql://postgres:postgres@localhost:5432/oli_test

    steps:
      - name: 🛎️ Checkout
        uses: actions/checkout@v4

      - name: 🔧 Configure
        run: |
          cp oli.example.env oli.env

      - name: 🧪 Setup elixir
        uses: erlef/setup-elixir@v1
        with:
          elixir-version: 1.19.2
          otp-version: 28.1.1

      - name: ⬇️ Install elixir dependencies
        run: mix deps.get

      - name: 🔨 Build dependencies
        run: mix deps.compile

      - name: 🔨 Build project
        run: set -a; source oli.env && mix compile --warnings-as-errors

      - name: 📋 Check Formatting
        run: mix format --check-formatted

      - name: ▶️ Run unit tests
        run: |
          set -a;source oli.env
          MIX_ENV=test mix ecto.reset
          mix test --trace || if [[ $? = 2  ]]; then mix test --failed; else false; fi

      - name: 📦 Install node_module dependencies
        run: yarn --cwd assets --frozen-lockfile

  ts-build-test:
    name: TypeScript build and test
    runs-on: ubuntu-latest

    steps:
      - name: 🛎️ Checkout
        uses: actions/checkout@v4

      - name: 🔧 Configure
        uses: actions/setup-node@v1
        with:
          node-version: "16.14.2"

      - name: 🧪 Setup elixir
        uses: erlef/setup-elixir@v1
        with:
          elixir-version: 1.19.2
          otp-version: 28.1.1

      - name: ⬇️ Install elixir dependencies
        run: mix deps.get

      - name: 📦 Install node_module dependencies
        run: yarn --cwd assets --frozen-lockfile

      - name: 🧹 Lint
        run: yarn --cwd assets run prettier && yarn --cwd assets run lint

      - name: 👁️ Typecheck
        run: yarn --cwd assets run check-types

      - name: 🔨 Build
        run: yarn --cwd assets run deploy

      - name: ⚙️ Test
        run: yarn --cwd assets run test
