name: Documentation
on:
  push:
    branches:
      - master
  # manually trigger a package build from the Actions tab
  workflow_dispatch:

jobs:
  docs:
    runs-on: ubuntu-latest
    # only deploy docs if the workflow is running on the master branch
    if: github.ref == 'refs/heads/master'

    steps:
      - name: 🛎️ Checkout
        uses: actions/checkout@v2 # If you're using actions/checkout@v2 you must set persist-credentials to false in most cases for the deployment to work correctly.
        with:
          persist-credentials: false

      - name: 🔧 Setup
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: yarn
          cache-dependency-path: assets/yarn.lock

      - name: 🔧 Configure
        run: cp oli.example.env oli.env

      - name: 🧪 Setup BEAM toolchain
        uses: erlef/setup-beam@v1
        with:
          elixir-version: 1.19.2 # Define the elixir version [required]
          otp-version: 28.1.1 # Define the OTP version [required]
          gleam-version: "1.16.0"

      - name: ⬇️ Install Gleam Mix archive
        run: |
          mix local.hex --force
          mix local.rebar --force
          mix archive.install hex mix_gleam 0.6.2 --force

      - name: ⬇️ Install Elixir Dependencies
        run: mix deps.get

      - name: 🔨 Build Gleam project
        run: gleam build --target erlang
        working-directory: gleam

      - name: 🔨📦 Build Dependencies
        run: mix deps.compile

      - name: Install node_module dependencies 📦
        run: npm install -g yarn && yarn --cwd assets

      - name: Build client-side API markdown docs
        run: yarn --cwd assets run sdk-docs

      - name: 🔨📄 Build Docs
        run: mix docs

      - name: 🔨📖 Build client-side storybook docs
        run: yarn --cwd assets run storybook:build

      - name: 🚀 Deploy Docs
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: doc # The folder the action should deploy.
