name: Pull Request CI Checks

on:
  pull_request:
    branches:
      - master
      - test
      - production

jobs:
  elixir-build-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup Configuration
      run: cp oli.example.env oli.env && cp postgres.example.env postgres.env
    - name: Start Test Database
      run: docker-compose up -d postgres
    - name: Setup elixir
      uses: actions/setup-elixir@v1
      with:
        elixir-version: 1.9.2 # Define the elixir version [required]
        otp-version: 22.2 # Define the OTP version [required]
    - name: Install Dependencies
      run: mix deps.get
    - name: Run Tests
      run: mix test

  ts-build-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Setup elixir
      uses: actions/setup-elixir@v1
      with:
        elixir-version: 1.9.2 # Define the elixir version [required]
        otp-version: 22.2 # Define the OTP version [required]
    - name: Install Elixir Dependencies
      run: mix deps.get
    - name: Install node_module Dependencies
      run: cd assets && npm install
    - name: Lint
      run: cd assets && npm run lint
    - name: Build
      run: cd assets && npm run deploy
    - name: Test
      run: cd assets && npm run test

