name: Preview Teardown

on:
  pull_request:
    types: [closed]

jobs:
  teardown:
    runs-on: plasma
    env:
      PR: ${{ github.event.number }}
      KUBECONFIG: /etc/rancher/k3s/k3s.yaml
    steps:
      - uses: actions/checkout@v4

      - name: Uninstall Helm release
        run: |
          helm uninstall "pr-${PR}" --namespace "pr-${PR}" || true

      - name: Delete namespace
        run: kubectl delete namespace "pr-${PR}" --ignore-not-found --wait=false

      - name: Remove preview comment
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          delete: true
